trunk/Penates/Penates/Models/ViewModels/ABMs/ABMViewModel.cs
using Penates.Exceptions.Database;
using Penates.Models.ViewModels.Forms;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Penates.Models.ViewModels.ABMs {
    public class ABMViewModel {

        public ABMViewModel() {
            this.tableID = "table";
            this.tableRefresh = "refreshTable";
            this.tableDelete = "DeleteEvent";
            this.Error = false;
        }

        public string Message { get; set; }

        public bool? Error { get; set; }

        public long? SelectedValue { get; set; }

        public IEnumerable<SelectListItem> List { get; set; }

        public string AjaxRequest { get; set; }

        public long filterID { get; set; }

        public string tableID { get; set; }

        public string tableRefresh { get; set; }

        public string tableDelete { get; set; }
    }
}

trunk/Penates/Penates/Models/ViewModels/ABMs/ConstraintViewModel.cs
using Penates.Utils.Objects;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Penates.Models.ViewModels.ABMs {
    public class ConstraintViewModel {

        public ConstraintViewModel(string title) {
            this.Title = title;
        }

        public ConstraintViewModel(string title, string message) {
            this.Title = title;
            this.Message = message;
        }

        public string Title{get; set;}

        public string Message { get; set; }

        public long Count { get; set; }

        public string TableWithConstrain { get; set; }

        public List<Constraint> constraints { get; set; }
    }
}

trunk/Penates/Penates/Models/ViewModels/ABMs/SupplierABMViewModel.cs
using Penates.Exceptions.Database;
using Penates.Models.ViewModels.Forms;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Penates.Models.ViewModels.ABMs {
    public class SupplierABMViewModel : ABMViewModel{

        public SupplierABMViewModel() {

        }

        public long? ProductID { get; set; }

        public string ProductName { get; set; }
    }
}

trunk/Penates/Penates/Controllers/ABMs/ClientsABMController.cs
using Penates.Database;
using Penates.Exceptions.Database;
using Penates.Interfaces.Services;
using Penates.Models;
using Penates.Models.ViewModels.ABMs;
using Penates.Services;
using Penates.Services.ABMs;
using Penates.Services.Geography;
using Penates.Utils;
using Penates.Utils.Enums;
using Penates.Utils.JSON.TableObjects;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Penates.Controllers.ABMs
{
    public class ClientsABMController : Controller
    {
        [RoleValidation(RoleType.SU, RoleType.InventoryChief, RoleType.Common, RoleType.Executive)]
        public ActionResult Index(ABMViewModel model) {
            if (model == null) {
                model = new ABMViewModel();
            }
            IGeoService service = new GeoService();
            model.List = service.getCountryList(true);

            List<SelectListItem> typeList = new List<SelectListItem>();
            SelectListItem i = new SelectListItem();
            i.Text = Resources.Resources.All;
            i.Value = DeactivatedTypes.ALL.getTypeNumber().ToString();
            typeList.Add(i);
            i = new SelectListItem();
            i.Text = Penates.App_GlobalResources.Forms.ModelFormsResources.Active;
            i.Value = DeactivatedTypes.ACTIVE.getTypeNumber().ToString(); ;
            typeList.Add(i);
            i = new SelectListItem();
            i.Text = Penates.App_GlobalResources.Forms.ModelFormsResources.Deactivated;
            i.Value = DeactivatedTypes.DEACTIVATED.getTypeNumber().ToString(); ;
            typeList.Add(i);
            ViewBag.AnnulatedList = typeList;
            return View("~/Views/ABMS/ClientsABM.cshtml", model);
        }

        [RoleValidation(RoleType.SU, RoleType.InventoryChief, RoleType.Common, RoleType.Executive)]
        public ActionResult GetTable(jQueryDataTableParamModel param, long? SelectedValue, long? ProvinceID, long? CityID, int? Annulated) {
            try {
                IClientService service = new ClientService();
                int sortColumnIndex = Convert.ToInt32(Request["iSortCol_0"]);
                string sortDirection = Request["sSortDir_0"];
                IQueryable<Client> query = service.getData(true);
                query = service.filterByCountry(query, SelectedValue);
                query = service.filterByState(query, ProvinceID);
                query = service.filterByCity(query, CityID);
                query = service.filterByDeactivated(query, Annulated);
                query = service.sort(query, sortColumnIndex, sortDirection);
                long total = query.Count(); //El total sin paginacion
                Paginator<Client> pag = new Paginator<Client>(query);
                query = pag.page(param.iDisplayStart, param.iDisplayLength);
                List<ClientTableJson> result = service.toJsonArray(query);
                long count = result.Count();
                return Json(new {
                    sEcho = param.sEcho,
                    iTotalRecords = count,
                    iTotalDisplayRecords = total,
                    aaData = result
                },
                            JsonRequestBehavior.AllowGet);
            } catch (DatabaseException ex) {
                ErrorModel errorModel = new ErrorModel(ex.title, ex.Message, ex, this.ControllerContext.RouteData.Values["controller"].ToString(), this.ControllerContext.RouteData.Values["action"].ToString());
                return View("~/Views/Error/ErrorDisplay.cshtml", errorModel);
            } catch (Exception e) {
                ErrorModel errorModel = new ErrorModel(Resources.Errors.DatabaseError, e, this.ControllerContext.RouteData.Values["controller"].ToString(), this.ControllerContext.RouteData.Values["action"].ToString());
                return View("~/Views/Error/ErrorDisplay.cshtml", errorModel);
            }
        }

        /// <summary>Elimina el centro de distribucion con determinado id del sistema /// </summary>
        /// <param name="id">Id del producto a eliminar</param>
        /// <returns>El menu de ABM o en caso de tener una constrain la lista de constrains</returns>
        [RoleValidation(RoleType.SU, RoleType.InventoryChief, RoleType.Common, RoleType.Executive)]
        public ActionResult Annulate(long ClientID) {
            IClientService service = new ClientService();
            try {
                Status result = service.Deactivate(ClientID);
                if (result.Success) {
                    return Json(new {
                        title = Resources.Messages.OperationSuccessfull,
                        message = result.Message
                    }, JsonRequestBehavior.AllowGet);
                } else {
                    Response.StatusCode = 511;
                    Response.StatusDescription = Resources.Errors.OperationUnsaccessfull;
                    Response.Write(result.Message);
                    return null;
                }
            } catch (DatabaseException ex) {
                Response.StatusCode = 511;
                Response.StatusDescription = ex.title;
                Response.Write(ex.Message);
                return null;
            } catch (Exception e) {
                Response.StatusCode = 511;
                Response.StatusDescription = Resources.Errors.OperationUnsaccessfull;
                Response.Write(e.Message);
                return null;
            }
        }

        [RoleValidation(RoleType.All)]
        public JsonResult Autocomplete(string term) {
            try {
                IClientService service = new ClientService();
                var items = service.getAutocomplete(term, false);
                var json = service.toJsonAutocomplete(items);
                return Json(json, JsonRequestBehavior.AllowGet);
            } catch (DatabaseException ex) {
                Response.StatusCode = 504;
                Response.StatusDescription = ex.title;
                Response.Write(ex.Message);
                return null;
            } catch (Exception e) {
                Response.StatusCode = 504;
                Response.StatusDescription = Resources.Errors.DatabaseError;
                Response.Write(e.Message);
                return null;
            }
        }
    }
}

trunk/Penates/Penates/Controllers/ABMs/ItemStatesABMController.cs
using Penates.Database;
using Penates.Exceptions.Database;
using Penates.Interfaces.Services;
using Penates.Models;
using Penates.Models.ViewModels.ABMs;
using Penates.Services;
using Penates.Services.ABMs;
using Penates.Utils.Enums;
using Penates.Utils.JSON.TableObjects;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Penates.Controllers.ABMs
{
    public class ItemStatesABMController : Controller
    {
        [RoleValidation(RoleType.SU, RoleType.InventoryChief, RoleType.Common)]
        public ActionResult Index(ABMViewModel model) {
            if (model == null) {
                model = new ABMViewModel();
            }
            return View("~/Views/ABMS/ItemStatesABM.cshtml", model);
        }

        [RoleValidation(RoleType.SU, RoleType.InventoryChief, RoleType.Common)]
        public ActionResult GetTable(jQueryDataTableParamModel param) {
            try {
                IStatusService service = new StatusService();
                IQueryable<ItemsState> query = service.getData();
                List<StatusTableJson> result = service.toJsonArray(query);
                return Json(new {
                    sEcho = param.sEcho,
                    aaData = result
                },
                            JsonRequestBehavior.AllowGet);
            } catch (DatabaseException ex) {
                ErrorModel errorModel = new ErrorModel(ex.title, ex.Message, ex, this.ControllerContext.RouteData.Values["controller"].ToString(), this.ControllerContext.RouteData.Values["action"].ToString());
                return View("~/Views/Error/ErrorDisplay.cshtml", errorModel);
            } catch (Exception e) {
                ErrorModel errorModel = new ErrorModel(Resources.Errors.DatabaseError, e, this.ControllerContext.RouteData.Values["controller"].ToString(), this.ControllerContext.RouteData.Values["action"].ToString());
                return View("~/Views/Error/ErrorDisplay.cshtml", errorModel);
            }
        }

        /// <summary>Elimina el centro de distribucion con determinado id del sistema /// </summary>
        /// <param name="id">Id del producto a eliminar</param>
        /// <returns>El menu de ABM o en caso de tener una constrain la lista de constrains</returns>
        [RoleValidation(RoleType.SU, RoleType.InventoryChief, RoleType.Common)]
        public ActionResult Delete(long StatusID) {
            IStatusService service = new StatusService();
            try {
                bool result = service.Delete(StatusID);
                if (result) {
                    return Json(new {
                        title = Resources.Messages.OperationSuccessfull,
                        message = String.Format(Resources.Messages.DeletedItem, Resources.Resources.ItemStateWArt, StatusID)
                    }, JsonRequestBehavior.AllowGet);
                } else {
                    Response.StatusCode = 511;
                    Response.StatusDescription = Resources.Errors.OperationUnsaccessfull;
                    Response.Write(String.Format(Resources.Errors.AlreadyDeletedAlert, Resources.Resources.ItemStateWArt, StatusID));
                    return null;
                }
            } catch (DatabaseException ex) {
                Response.StatusCode = 511;
                Response.StatusDescription = ex.title;
                Response.Write(ex.Message);
                return null;
            } catch (Exception e) {
                Response.StatusCode = 511;
                Response.StatusDescription = Resources.Errors.OperationUnsaccessfull;
                Response.Write(e.Message);
                return null;
            }
        }

        [RoleValidation(RoleType.All)]
        public JsonResult Autocomplete(string term) {
            try {
                IStatusService service = new StatusService();
                var items = service.getAutocomplete(term);
                var json = service.toJsonAutocomplete(items);
                return Json(json, JsonRequestBehavior.AllowGet);
            } catch (DatabaseException ex) {
                Response.StatusCode = 504;
                Response.StatusDescription = ex.title;
                Response.Write(ex.Message);
                return null;
            } catch (Exception e) {
                Response.StatusCode = 504;
                Response.StatusDescription = Resources.Errors.DatabaseError;
                Response.Write(e.Message);
                return null;
            }
        }
    }
}

trunk/Penates/Penates/Controllers/ABMs/PacksABMController.cs
using Penates.Database;
using Penates.Exceptions.Database;
using Penates.Interfaces.Services;
using Penates.Models;
using Penates.Models.ViewModels.ABMs;
using Penates.Services;
using Penates.Services.ABMs;
using Penates.Utils.Enums;
using Penates.Utils.JSON.TableObjects;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Penates.Controllers.ABMs
{
    public class PacksABMController : Controller
    {
        [RoleValidation(RoleType.SU, RoleType.InventoryChief, RoleType.Common)]
        public ActionResult Index(ABMViewModel model) {
            if (model == null) {
                model = new ABMViewModel();
            }
            return View("~/Views/ABMS/PacksABM.cshtml", model);
        }

        [RoleValidation(RoleType.SU, RoleType.InventoryChief, RoleType.Common)]
        public ActionResult GetTable(jQueryDataTableParamModel param) {
            try {
                IPackService service = new PackService();
                IQueryable<Pack> query = service.getData();
                List<PackTableJson> result = service.toJsonArray(query);
                return Json(new {
                    sEcho = param.sEcho,
                    aaData = result
                },
                            JsonRequestBehavior.AllowGet);
            } catch (DatabaseException ex) {
                ErrorModel errorModel = new ErrorModel(ex.title, ex.Message, ex, this.ControllerContext.RouteData.Values["controller"].ToString(), this.ControllerContext.RouteData.Values["action"].ToString());
                return View("~/Views/Error/ErrorDisplay.cshtml", errorModel);
            } catch (Exception e) {
                ErrorModel errorModel = new ErrorModel(Resources.Errors.DatabaseError, e, this.ControllerContext.RouteData.Values["controller"].ToString(), this.ControllerContext.RouteData.Values["action"].ToString());
                return View("~/Views/Error/ErrorDisplay.cshtml", errorModel);
            }
        }

        /// <summary>Elimina el centro de distribucion con determinado id del sistema /// </summary>
        /// <param name="id">Id del producto a eliminar</param>
        /// <returns>El menu de ABM o en caso de tener una constrain la lista de constrains</returns>
        [RoleValidation(RoleType.SU, RoleType.InventoryChief, RoleType.Common)]
        public ActionResult Delete(long PackID) {
            IPackService service = new PackService();
            try {
                bool result = service.Delete(PackID);
                if (result) {
                    return Json(new {
                        title = Resources.Messages.OperationSuccessfull,
                        message = String.Format(Resources.Messages.DeletedItem, Resources.Resources.PackWArt, PackID)
                    }, JsonRequestBehavior.AllowGet);
                } else {
                    Response.StatusCode = 511;
                    Response.StatusDescription = Resources.Errors.OperationUnsaccessfull;
                    Response.Write(String.Format(Resources.Errors.AlreadyDeletedAlert, Resources.Resources.PackWArt, PackID));
                    return null;
                }
            } catch (DatabaseException ex) {
                Response.StatusCode = 511;
                Response.StatusDescription = ex.title;
                Response.Write(ex.Message);
                return null;
            } catch (Exception e) {
                Response.StatusCode = 511;
                Response.StatusDescription = Resources.Errors.OperationUnsaccessfull;
                Response.Write(e.Message);
                return null;
            }
        }

        [RoleValidation(RoleType.All)]
        public JsonResult Autocomplete(string term) {
            try {
                IPackService service = new PackService();
                var items = service.getAutocomplete(term);
                var json = service.toJsonAutocomplete(items);
                return Json(json, JsonRequestBehavior.AllowGet);
            } catch (DatabaseException ex) {
                Response.StatusCode = 504;
                Response.StatusDescription = ex.title;
                Response.Write(ex.Message);
                return null;
            } catch (Exception e) {
                Response.StatusCode = 504;
                Response.StatusDescription = Resources.Errors.DatabaseError;
                Response.Write(e.Message);
                return null;
            }
        }
    }
}

trunk/Penates/Penates/Views/ABMs/ClientsABM.cshtml
@model Penates.Models.ViewModels.ABMs.ABMViewModel
@using Penates.Models

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!doctype html>
<html>
<head>
    <title>@Html.Resource("Title")</title>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-extension.css" rel="stylesheet" />
    <script src="~/Scripts/Plugins/globalParams.js"></script>
    <meta charset=utf-8 />
    
    <script type="text/javascript" title="Global Parameters">
        var globalParams = new ParametrosGlobales();
    </script>

    <script>
        $(document).ready(function () {
            $("#tableRefresh").click(function (e) {
                window["@Model.tableRefresh"]();
            });

            $("#SelectedValue").change(function (e) {
                var selectedVal = $("#SelectedValue").val();
                $.getJSON('@Url.Action("GetStatesAll", "Geography")', {countryID: selectedVal}, function (states) {
                    var list = $('select#StateSelectList');
                    list.find('option').remove();
                    $(states).each(function (index, state) {
                        list.append('<option value="' + state.Value + '">' + state.Text + '</option>');
                    });
                }).fail(function(){
                    alert("Error loading state");
                });
                if (selectedVal == -1) {
                    $("#stateList").hide();
                    $("#cityList").hide();
                    globalParams.deleteParam("ProvinceID");
                    globalParams.deleteParam("CityID");
                } else {
                    $("#stateList").show();
                }
                globalParams.addParam("SelectedValue", selectedVal);
                window["@Model.tableRefresh"]();
            });
            
            $("#StateSelectList").change(function (e) {
                var selectedVal = $("#StateSelectList").val();
                $.getJSON('@Url.Action("GetCitiesAll", "Geography")', { provinceID: selectedVal }, function (cities) {
                    var list = $('select#CitySelectList');
                    list.find('option').remove();
                    $(cities).each(function (index, city) {
                        list.append('<option value="' + city.Value + '">' + city.Text + '</option>');
                    });
                }).fail(function () {
                    alert("Error loading city");
                });
                if (selectedVal == -1) {
                    $("#cityList").hide();
                    globalParams.deleteParam("CityID");
                } else {
                    $("#cityList").show();
                }
                globalParams.addParam("SelectedValue", $("#SelectedValue").val());
                globalParams.addParam("ProvinceID", selectedVal);
                window["@Model.tableRefresh"]();
            });

            $("#CitySelectList").change(function (e) {
                globalParams.addParam("SelectedValue", $("#SelectedValue").val());
                globalParams.addParam("ProvinceID", $("#StateSelectList").val());
                globalParams.addParam("CityID", $("#CitySelectList").val());
                window["@Model.tableRefresh"]();
            });

            $("#AnnulatedSelectList").change(function (e) {
                globalParams.addParam("Annulated", $("#AnnulatedSelectList").val());
                window["@Model.tableRefresh"]();
            });
        });
    </script>

    <script type="text/javascript" title="Clear Form Data">
        $(document).ready(function () {
            sessionStorage.clear();
        });
    </script>

</head>
<body>
    <div class="container">
        <div class="row">
            <h3>@Html.Resource("Title")</h3>
            @if (@Model.Message != null && @Model.Error != null && @Model.Message != "") {
                if (@Model.Error == true) {
                    <div class="alert alert-dismissable alert-danger">
                        <button type="button" class="close" data-dismiss="alert">×</button>
                        @Model.Message
                    </div>
                } else {
                    <div class="alert alert-dismissable alert-success">
                        <button type="button" class="close" data-dismiss="alert">×</button>
                        @Model.Message
                    </div>
                }
            }
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="row">
                        <div class="col-sm-1">
                            <a class="btn btn-success btn-lg btn-xs" onclick="location.href='@Url.Action("Index", "ClientForms")'">
                                <span class="glyphicon glyphicon-plus"></span>
                            </a>
                            <a id="tableRefresh" class="btn btn-default btn-lg btn-xs">
                                <span class="glyphicon glyphicon-refresh"></span>
                            </a>
                        </div>
                        <label class="col-sm-2 control-label">@Html.Resource("CountryList"):</label>
                        <div class="col-sm-3">
                            @Html.DropDownListFor(model => model.SelectedValue, Model.List, new { @class = "form-control input-sm" })
                        </div>
                        <div id="stateList" hidden="hidden">
                            @{
                                List<SelectListItem> stateListInitialize = new List<SelectListItem>();
                                SelectListItem i = new SelectListItem();
                                i.Text = Resources.Resources.All;
                                i.Value = "-1";
                                stateListInitialize.Add(i);
                            }
                            <label class="col-sm-2 control-label">@Html.Resource("ProvinceList"):</label>
                            <div class="col-sm-3">
                                @Html.DropDownList("StateSelectList", new SelectList(stateListInitialize, "Value", "Text"), new { @class = "form-control input-sm" })
                            </div>
                        </div>
                    </div><br />
                    <div class="row">
                        <div class="col-sm-1"></div>
                        <div id="cityList" hidden="hidden">
                            @{
                                List<SelectListItem> cityListInitialize = new List<SelectListItem>();
                                SelectListItem j = new SelectListItem();
                                j.Text = Resources.Resources.All;
                                j.Value = "-1";
                                cityListInitialize.Add(j);
                            }
                            <label class="col-sm-2 control-label">@Html.Resource("CityList"):</label>
                            <div class="col-sm-3">
                                @Html.DropDownList("CitySelectList", new SelectList(cityListInitialize, "Value", "Text"), new { @class = "form-control input-sm" })
                            </div>
                        </div>
                        <label class="col-sm-2 control-label">@Html.Resource("AnnulatedList"):</label>
                        <div class="col-sm-2">
                            @Html.DropDownList("AnnulatedSelectList", new SelectList(ViewBag.AnnulatedList, "Value", "Text"), new { @class = "form-control input-sm" })
                        </div>
                    </div>
                </div>
            </div>
        </div>
        @{Html.RenderPartial("~/Views/ABMs/Tables/_ClientsTable.cshtml", new TableAjaxViewModel(@Model.tableID) {
            AjaxRequest = Url.Action("GetTable", "ClientsABM"),
            DeleteAction = "Annulate",
            DeleteController = "ClientsABM",
            DeleteText = Resources.FormsResources.Deactivate,
            ToggleDeleteMessage = true,
            DeleteText2 = Resources.FormsResources.Activate,
            RefreshFunction = @Model.tableRefresh,
            ServerProcessing = true
        });}
    </div>
</body>
</html>

trunk/Penates/Penates/Views/ABMs/ItemStatesABM.cshtml
@model Penates.Models.ViewModels.ABMs.ABMViewModel
@using Penates.Models

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!doctype html>
<html>
<head>
    <title>@Html.Resource("Title")</title>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-extension.css" rel="stylesheet" />
    <meta charset=utf-8 />
    
    <script>
        $(document).ready(function () {
            $("#tableRefresh").click(function (e) {
                refreshTable();
            });

            $("#SelectedValue").change(function (e) {
                refreshTable();
            });

            sessionStorage.clear();
        });
    </script>
</head>
<body>
    <div class="container">
        <div class="row">
            <h3>@Html.Resource("Title")</h3>
            @if (@Model.Message != null && @Model.Error != null && @Model.Message != "") {
                if (@Model.Error == true) {
                    <div class="alert alert-dismissable alert-danger">
                        <button type="button" class="close" data-dismiss="alert">×</button>
                        @Model.Message
                    </div>
                } else {
                    <div class="alert alert-dismissable alert-success">
                        <button type="button" class="close" data-dismiss="alert">×</button>
                        @Model.Message
                    </div>
                }
            }
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="row">
                        <div class="col-sm-2">
                            <a class="btn btn-success btn-lg btn-xs" onclick="location.href='@Url.Action("Index", "ItemStatesForms")'">
                                <span class="glyphicon glyphicon-plus"></span>
                            </a>
                            <a id="tableRefresh" class="btn btn-default btn-lg btn-xs">
                                <span class="glyphicon glyphicon-refresh"></span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            @{Html.RenderPartial("~/Views/ABMs/Tables/_ItemsStatesTable.cshtml", new TableAjaxViewModel(@Model.tableID) { 
                  AjaxRequest = @Url.Action("GetTable","ItemStatesABM"),
                  DeleteAction = "Delete",
                  DeleteController = "ItemStatesABM",
                  DeleteText = Resources.FormsResources.Delete,
                  DeleteConfirmMessage = String.Format(Resources.Messages.SureToDelete, Resources.Resources.ItemStateWArt),
                  RefreshFunction = "refreshTable",
                  ServerProcessing = false
              });}
        </div>
    </div>
</body>
</html>

trunk/Penates/Penates/Views/ABMs/PacksABM.cshtml
@model Penates.Models.ViewModels.ABMs.ABMViewModel
@using Penates.Models

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!doctype html>
<html>
<head>
    <title>@Html.Resource("Title")</title>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-extension.css" rel="stylesheet" />
    <meta charset=utf-8 />
    
    <script>
        $(document).ready(function () {
            $("#tableRefresh").click(function (e) {
                refreshTable();
            });

            $("#SelectedValue").change(function (e) {
                refreshTable();
            });

            sessionStorage.clear();
        });
    </script>
</head>
<body>
    <div class="container">
        <div class="row">
            <h3>@Html.Resource("Title")</h3>
            @if (@Model.Message != null && @Model.Error != null && @Model.Message != "") {
                if (@Model.Error == true) {
                    <div class="alert alert-dismissable alert-danger">
                        <button type="button" class="close" data-dismiss="alert">×</button>
                        @Model.Message
                    </div>
                } else {
                    <div class="alert alert-dismissable alert-success">
                        <button type="button" class="close" data-dismiss="alert">×</button>
                        @Model.Message
                    </div>
                }
            }
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="row">
                        <div class="col-sm-2">
                            <a class="btn btn-success btn-lg btn-xs" onclick="location.href='@Url.Action("Index", "PackForm")'">
                                <span class="glyphicon glyphicon-plus"></span>
                            </a>
                            <a id="tableRefresh" class="btn btn-default btn-lg btn-xs">
                                <span class="glyphicon glyphicon-refresh"></span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            @{Html.RenderPartial("~/Views/ABMs/Tables/_PacksTable.cshtml", new TableAjaxViewModel(@Model.tableID) { 
                  AjaxRequest = @Url.Action("GetTable","PacksABM"),
                  DeleteAction = "Delete",
                  DeleteController = "PacksABM",
                  DeleteText = Resources.FormsResources.Delete,
                  DeleteConfirmMessage = String.Format(Resources.Messages.SureToDelete, Resources.Resources.PackWArt),
                  RefreshFunction = "refreshTable",
                  ServerProcessing = false
              });}
        </div>
    </div>
</body>
</html>