trunk/Penates/Penates/Models/ViewModels/DC/DistributionCenterViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using DataAnnotationsExtensions;
using Penates.App_GlobalResources.Forms;
using Penates.Database;
using Penates.Utils;
using System.Drawing;
using System.Web.Helpers;
using Penates.Services.ABMs;
using Penates.Models.Validators;
using System.Web.Mvc;
using Penates.Interfaces.Models;

namespace Penates.Models.ViewModels.DC {
    public abstract class DistributionCenterViewModel : IFormViewModel {

        public DistributionCenterViewModel() {
            this.UsableSpace = 0;
            this.UsableUsedSpace = 0;

            List<SelectListItem> stateListInitialize = new List<SelectListItem>();
            SelectListItem stateIni = new SelectListItem();
            stateIni.Text = Resources.Messages.SelectState;
            stateIni.Value = "-1";
            stateListInitialize.Add(stateIni);
            this.StateList = new SelectList(stateListInitialize, "Value", "Text");

            List<SelectListItem> cityListInitialize = new List<SelectListItem>();
            SelectListItem cityIni = new SelectListItem();
            cityIni.Text = Resources.Messages.SelectCity;
            cityIni.Value = "-1";
            cityListInitialize.Add(cityIni);
            this.CityList = new SelectList(cityListInitialize, "Value", "Text");
        }

        [Display(Name = "DistributionCenterID", ResourceType = typeof(ModelFormsResources))]
        public long DistributionCenterID { get; set; }

        [Required(ErrorMessageResourceName = "RequiredError", ErrorMessageResourceType = typeof(Resources.FormsErrors))]
        [Range(0, Int64.MaxValue, ErrorMessageResourceName = "RangeError", ErrorMessageResourceType = typeof(Resources.FormsErrors))]
        [Display(Name = "CityID", ResourceType = typeof(ModelFormsResources))]
        public long CityID { get; set; }

        [Required(ErrorMessageResourceName = "RequiredError", ErrorMessageResourceType = typeof(Resources.FormsErrors))]
        [DataType(DataType.Text)]
        [StringLength(128, ErrorMessageResourceName = "LenghtError", ErrorMessageResourceType = typeof(Resources.FormsErrors))]
        [Display(Name = "Address", ResourceType = typeof(ModelFormsResources))]
        public string Address { get; set; }

        [Required(ErrorMessageResourceName = "RequiredError", ErrorMessageResourceType = typeof(Resources.FormsErrors))]
        [DataType(DataType.PhoneNumber)]
        [Phone(ErrorMessage = null, ErrorMessageResourceName = "PhoneError", ErrorMessageResourceType = typeof(Resources.FormsErrors))]
        [StringLength(128, ErrorMessageResourceName = "LenghtError", ErrorMessageResourceType = typeof(Resources.FormsErrors))]
        [Display(Name = "Telephone", ResourceType = typeof(ModelFormsResources))]
        public string Telephone { get; set; }

        [Numeric(ErrorMessageResourceName = "NumericTypeError", ErrorMessageResourceType = typeof(Resources.FormsErrors))]
        [Required(ErrorMessageResourceName = "RequiredError", ErrorMessageResourceType = typeof(Resources.FormsErrors))]
        [Range(0, 1E36, ErrorMessageResourceName = "RangeError", ErrorMessageResourceType = typeof(Resources.FormsErrors))]
        [DisplayFormat(DataFormatString = "{0:F2}")]
        [Display(Name = "UsableSpace", ResourceType = typeof(ModelFormsResources))]
        public decimal UsableSpace { get; set; }

        [Numeric(ErrorMessageResourceName = "NumericTypeError", ErrorMessageResourceType = typeof(Resources.FormsErrors))]
        [Required(ErrorMessageResourceName = "RequiredError", ErrorMessageResourceType = typeof(Resources.FormsErrors))]
        [Range(0, 1E36, ErrorMessageResourceName = "RangeError", ErrorMessageResourceType = typeof(Resources.FormsErrors))]
        [DisplayFormat(DataFormatString = "{0:F2}")]
        [Display(Name = "UsableUsedSpace", ResourceType = typeof(ModelFormsResources))]
        public decimal UsableUsedSpace { get; set; }

        [DisplayFormat(DataFormatString = "{0:F2}")]
        [Display(Name = "UsableSpacePercentage", ResourceType = typeof(ModelFormsResources))]
        public decimal UsableSpacePercentage { get; set; }

        public IEnumerable<SelectListItem> CountryList { get; set; }
        
        public long CountryID { get; set; }

        public long StateID { get; set; }

        public string CountryName { get; set; }

        public string StateName { get; set; }

        [Display(Name = "error")]
        public string error { get; set; }

        public string CityName { get; set; }

        public IEnumerable<SelectListItem> StateList { get; set; }

        public IEnumerable<SelectListItem> CityList { get; set; }

        public void setPrecentages() {
            if (this.UsableSpace == 0) {
                this.UsableSpacePercentage = 100;
            } else {
                this.UsableSpacePercentage = (this.UsableUsedSpace / this.UsableSpace) * 100;
            }
        }
    }
}

trunk/Penates/Penates/Controllers/DisCenter/Deposits/DepositsABMController.cs
using Penates.Database;
using Penates.Exceptions.Database;
using Penates.Interfaces.Services;
using Penates.Models;
using Penates.Models.ViewModels.ABMs;
using Penates.Services;
using Penates.Services.DC;
using Penates.Utils;
using Penates.Utils.Enums;
using Penates.Utils.JSON.TableObjects;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Penates.Controllers.DisCenter.Deposits
{
    public class DepositsABMController : Controller
    {
        [RoleValidation(RoleType.SU, RoleType.InventoryChief, RoleType.Common)]
        public ActionResult Index(ABMViewModel model) {
            if (model == null) {
                model = new ABMViewModel();
            }
            return View("~/Views/DistributionCenter/Deposits/DepositsABM.cshtml", model);
        }

        [RoleValidation(RoleType.SU, RoleType.InventoryChief, RoleType.Common)]
        public ActionResult GetTable(jQueryDataTableParamModel param, long? DistributionCenterID) {
            try {
                IDepositService service = new DepositService();
                IQueryable<Deposit> query = service.getData(DistributionCenterID);
                List<DepositTableJson> result = service.toJsonArray(query);
                return Json(new {
                    sEcho = param.sEcho,
                    aaData = result
                },
                            JsonRequestBehavior.AllowGet);
            } catch (DatabaseException ex) {
                ErrorModel errorModel = new ErrorModel(ex.title, ex.Message, ex, this.ControllerContext.RouteData.Values["controller"].ToString(), this.ControllerContext.RouteData.Values["action"].ToString());
                return View("~/Views/Error/ErrorDisplay.cshtml", errorModel);
            } catch (Exception e) {
                ErrorModel errorModel = new ErrorModel(Resources.Errors.DatabaseError, e, this.ControllerContext.RouteData.Values["controller"].ToString(), this.ControllerContext.RouteData.Values["action"].ToString());
                return View("~/Views/Error/ErrorDisplay.cshtml", errorModel);
            }
        }

        /// <summary>Elimina el centro de distribucion con determinado id del sistema /// </summary>
        /// <param name="id">Id del producto a eliminar</param>
        /// <returns>El menu de ABM o en caso de tener una constrain la lista de constrains</returns>
        [RoleValidation(RoleType.SU, RoleType.InventoryChief, RoleType.Common)]
        public ActionResult Delete(long DepositID) {
            IDepositService dcService = new DepositService();
            try {
                bool result = dcService.Delete(DepositID);
                if (result) {
                    return Json(new {
                        title = Resources.Messages.OperationSuccessfull,
                        message = String.Format(Resources.Messages.DeletedItem, Resources.Resources.DepositWArt, DepositID)
                    }, JsonRequestBehavior.AllowGet);
                } else {
                    Response.StatusCode = 511;
                    Response.StatusDescription = Resources.Errors.OperationUnsaccessfull;
                    Response.Write(String.Format(Resources.Errors.AlreadyDeletedAlert, Resources.Resources.DepositWArt, DepositID));
                    return null;
                }
            } catch (DatabaseException ex) {
                Response.StatusCode = 511;
                Response.StatusDescription = ex.title;
                Response.Write(ex.Message);
                return null;
            } catch (Exception e) {
                Response.StatusCode = 511;
                Response.StatusDescription = Resources.Errors.OperationUnsaccessfull;
                Response.Write(e.Message);
                return null;
            }
        }

        [RoleValidation(RoleType.All)]
        public JsonResult DistributionCenterAutocomplete(string term) {
            try {
                IDistributionCenterService service = new DistributionCenterService();
                var items = service.getInternalAutocomplete(term);
                var json = service.toJsonAutocomplete(items);
                return Json(json, JsonRequestBehavior.AllowGet);
            } catch (DatabaseException ex) {
                Response.StatusCode = 504;
                Response.StatusDescription = ex.title;
                Response.Write(ex.Message);
                return null;
            } catch (Exception e) {
                Response.StatusCode = 504;
                Response.StatusDescription = Resources.Errors.DatabaseError;
                Response.Write(e.Message);
                return null;
            }
        }

        [RoleValidation(RoleType.All)]
        public JsonResult Autocomplete(string term, long? DistributionCenterID) {
            try {
                IDepositService service = new DepositService();
                var items = service.getAutocomplete(term, DistributionCenterID);
                var json = service.toJsonAutocomplete(items);
                return Json(json, JsonRequestBehavior.AllowGet);
            } catch (DatabaseException ex) {
                Response.StatusCode = 504;
                Response.StatusDescription = ex.title;
                Response.Write(ex.Message);
                return null;
            } catch (Exception e) {
                Response.StatusCode = 504;
                Response.StatusDescription = Resources.Errors.DatabaseError;
                Response.Write(e.Message);
                return null;
            }
        }

        [RoleValidation(RoleType.All)]
        public JsonResult AutocompleteAll(string term, long? DistributionCenterID) {
            try {
                IDepositService service = new DepositService();
                var items = service.getAutocomplete(term, DistributionCenterID);
                var json = service.toJsonAutocomplete(items);
                ITemporaryDepositService tempService = new TemporaryDepositService();
                var tempItems = tempService.getAutocomplete(term, DistributionCenterID);
                var tempJson = tempService.toJsonAutocomplete(tempItems);
                json = ListUtils<AutocompleteItem>.interlay(json, tempJson);
                return Json(json, JsonRequestBehavior.AllowGet);
            } catch (DatabaseException ex) {
                Response.StatusCode = 504;
                Response.StatusDescription = ex.title;
                Response.Write(ex.Message);
                return null;
            } catch (Exception e) {
                Response.StatusCode = 504;
                Response.StatusDescription = Resources.Errors.DatabaseError;
                Response.Write(e.Message);
                return null;
            }
        }
    }
}

trunk/Penates/Penates/Controllers/DisCenter/Deposits/TemporaryDepositsABMController.cs
using Penates.Database;
using Penates.Exceptions.Database;
using Penates.Interfaces.Services;
using Penates.Models;
using Penates.Models.ViewModels.ABMs;
using Penates.Services;
using Penates.Services.DC;
using Penates.Utils.Enums;
using Penates.Utils.JSON.TableObjects;
using System;
using System.Collections.Generic;
using System.Data.Entity.SqlServer;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Penates.Controllers.DisCenter.Deposits
{
    [RoleValidation(RoleType.SU, RoleType.InventoryChief, RoleType.Common)]
    public class TemporaryDepositsABMController : Controller
    {
        public ActionResult Index(ABMViewModel model) {
            if (model == null) {
                model = new ABMViewModel();
            }
            return View("~/Views/DistributionCenter/Deposits/TemporaryDepositsABM.cshtml",model);
        }

        public ActionResult GetTable(jQueryDataTableParamModel param, long? DistributionCenterID) {
            try {
                ITemporaryDepositService service = new TemporaryDepositService();
                IQueryable<TemporaryDeposit> query = service.getData(DistributionCenterID);
                List<DepositTableJson> result = service.toJsonArray(query);
                return Json(new {
                    sEcho = param.sEcho,
                    aaData = result
                },
                            JsonRequestBehavior.AllowGet);
            } catch (DatabaseException ex) {
                ErrorModel errorModel = new ErrorModel(ex.title, ex.Message, ex, "FormsController", "SubmitProduct");
                return View("~/Views/Error/ErrorDisplay.cshtml", errorModel);
            } catch (Exception e) {
                ErrorModel errorModel = new ErrorModel(Resources.Errors.DatabaseError, e, "FormsController", "SubmitProduct");
                return View("~/Views/Error/ErrorDisplay.cshtml", errorModel);
            }
        }

        /// <summary>Elimina el centro de distribucion con determinado id del sistema /// </summary>
        /// <param name="id">Id del producto a eliminar</param>
        /// <returns>El menu de ABM o en caso de tener una constrain la lista de constrains</returns>
        public ActionResult Delete(long TemporaryDepositID) {
            ITemporaryDepositService dcService = new TemporaryDepositService();
            try {
                bool result = dcService.Delete(TemporaryDepositID);
                if (result) {
                    return Json(new {
                        title = Resources.Messages.OperationSuccessfull,
                        message = String.Format(Resources.Messages.DeletedItem, Resources.Resources.TemporaryDepositWArt, TemporaryDepositID)
                    }, JsonRequestBehavior.AllowGet);
                } else {
                    Response.StatusCode = 511;
                    Response.StatusDescription = Resources.Errors.OperationUnsaccessfull;
                    Response.Write(String.Format(Resources.Errors.AlreadyDeletedAlert, Resources.Resources.TemporaryDepositWArt, TemporaryDepositID));
                    return null;
                }
            } catch (DatabaseException ex) {
                Response.StatusCode = 511;
                Response.StatusDescription = ex.title;
                Response.Write(ex.Message);
                return null;
            } catch (Exception e) {
                Response.StatusCode = 511;
                Response.StatusDescription = Resources.Errors.OperationUnsaccessfull;
                Response.Write(e.Message);
                return null;
            }
        }

        [RoleValidation(RoleType.All)]
        public JsonResult Autocomplete(string term, long? DistributionCenterID) {
            try {
                ITemporaryDepositService service = new TemporaryDepositService();
                var items = service.getAutocomplete(term, DistributionCenterID);
                var json = service.toJsonAutocomplete(items);
                return Json(json, JsonRequestBehavior.AllowGet);
            } catch (DatabaseException ex) {
                Response.StatusCode = 504;
                Response.StatusDescription = ex.title;
                Response.Write(ex.Message);
                return null;
            } catch (Exception e) {
                Response.StatusCode = 504;
                Response.StatusDescription = Resources.Errors.DatabaseError;
                Response.Write(e.Message);
                return null;
            }
        }
	}
}

trunk/Penates/Penates/Views/DistributionCenter/Deposits/DepositFormSummary.cshtml
@model Penates.Models.ViewModels.DC.DepositViewModel

@{
    ViewBag.Title = "Product Form";
}
<!doctype html>
<html>
<head>
    <title>@Html.Resource("Title")</title>
    <meta charset="utf-8">
    <link href="~/Content/forms/images-sizes.css" rel="stylesheet" /> <!--Para hacer resize de las Imagenes-->
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-background.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-extension.css" rel="stylesheet" />
</head>

<body>
    <div class="container">
        <h2>@Html.Resource("Title")</h2>
        <div class="form-horizontal" id="deposit-form">
            <fieldset>
                <legend></legend>
                <div class="form-group">
                    <label class="col-lg-2 control-label">@Html.DisplayNameFor(m => m.DepositID):</label>
                    <div class="col-lg-4">
                        <p>@Model.DepositID</p>
                    </div>
                    <label class="col-lg-2 control-label">@Html.DisplayNameFor(m => m.Description):</label>
                    <div class="col-lg-4">
                        <p>@Model.Description</p>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-lg-2 control-label">@Html.DisplayNameFor(m => m.DistributionCenterID):</label>
                    <div class="col-lg-4">
                        <p>@Model.DistributionCenterID</p>
                    </div>
                    <label class="col-lg-2 control-label">@Html.DisplayNameFor(m => m.Floor):</label>
                    <div class="col-lg-4">
                        <p>@Model.Floor</p>
                    </div>
                </div>
                
                <!-- Size Info -->
                <fieldset id="product-form-sizeinfo" name="product-form-sizeinfo">
                    <legend>@Resources.FormsResources.SizeInfo:</legend>
                    <div class="form-group">
                        <label class="col-lg-1 control-label">* @Resources.FormsResources.Depth:</label>
                        <div class="col-lg-3">
                                <p>@Html.DisplayFor(m => m.Depth) m</p>
                        </div>
                        <label class="col-lg-1 control-label">* @Resources.FormsResources.Width:</label>
                        <div class="col-lg-3">
                                <p>@Html.DisplayFor(m => m.Width) m</p>
                        </div>
                        <label class="col-lg-1 control-label">* @Resources.FormsResources.Height:</label>
                        <div class="col-lg-3">
                                <p>@Html.DisplayFor(m => m.Height) m</p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-lg-2 col-lg-offset-3 control-label">* @Resources.FormsResources.Size:</label>
                        <div class="col-lg-4">
                                <p>@Html.DisplayFor(m => m.Size) m3</p>
                        </div>
                    </div>
                    <br>
                </fieldset>

                <!-- Capacity Info -->
                <fieldset id="product-form-sizeinfo" name="product-form-sizeinfo">
                    <legend>@Resources.FormsResources.CapacityInfo:</legend>
                    <div class="form-group">
                        <label class="col-lg-2 control-label">@Resources.FormsResources.Capacity:</label>
                        <div class="col-lg-2">
                                <p>@Html.DisplayFor(m => m.Size) m3</p>
                        </div>
                        <label class="col-lg-2 control-label">@Html.DisplayNameFor(m => m.UsedSpace):</label>
                        <div class="col-lg-2">
                                <p>@Html.DisplayFor(m => m.UsedSpace) m3</p>
                        </div>
                        <label class="col-lg-2 control-label">@Html.DisplayNameFor(m => m.UsedPercentage):</label>
                        <div class="col-lg-2">
                                <p>@Html.DisplayFor(m => m.UsedPercentage) %</p>
                        </div>
                    </div>
                    <br/>
                    <div class="form-group">
                        <label class="col-lg-2 control-label">@Html.DisplayNameFor(m => m.UsableSpace):</label>
                        <div class="col-lg-2">
                            <p>@Html.DisplayFor(m => m.UsableSpace) m3</p>
                        </div>
                        <label class="col-lg-2 control-label">@Html.DisplayNameFor(m => m.UsableUsedSpace):</label>
                        <div class="col-lg-2">
                            <p>@Html.DisplayFor(m => m.UsableUsedSpace) m3</p>
                        </div>
                        <label class="col-lg-2 control-label">@Html.DisplayNameFor(m => m.UsableSpacePercentage):</label>
                        <div class="col-lg-2">
                            <p>@Html.DisplayFor(m => m.UsableSpacePercentage) %</p>
                        </div>
                    </div>
                </fieldset>
                <br/>
                <div class="form-group">
                    <label class="col-lg-2 control-label">@Html.DisplayNameFor(m => m.Categories):</label>
                    <div class="col-lg-4">
                        <p>@Model.Categories</p>
                    </div>
                </div>
                <br>
                <div class="btn-toolbar center-block">
                    @Html.ActionLink(@Resources.FormsResources.Ok, "Index", "DepositsABM", new {SelectedValue = Model.DistributionCenterID }, new { @class = "btn btn-primary", @id = "Ok" })
                    @Html.ActionLink(@Resources.FormsResources.Edit, "FormEdit", "DepositsForms", new { DepositID = Model.DepositID }, new { @class = "btn btn-default", @id = "Edit" })
                    @Html.ActionLink(@Html.Resource("EditDistributionCenter"), "FormEdit", "DistributionCenterForms", new { id = Model.DistributionCenterID }, new { @class = "btn btn-default", @id = "EditDistributionCenter" })
                    @Html.ActionLink(@Html.Resource("AddSector"), "Index", "SectorsForms", new { DepositID = Model.DepositID }, new { @class = "btn btn-default", @id = "AddSector", @onclick = "sessionStorage.clear();" })
                    @Html.ActionLink(@Html.Resource("ViewSectors"), "Index", "SectorsABM", new { DepositID = Model.DepositID }, new { @class = "btn btn-default", @id = "ViewSectors" })
                </div>

            </fieldset>
        </div>
    </div>
</body>
</html>

trunk/Penates/Penates/Views/DistributionCenter/Deposits/TemporaryDepositsABM.cshtml
@model Penates.Models.ViewModels.ABMs.ABMViewModel
@using Penates.Models

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!doctype html>
<html>
<head>
    <title>@Html.Resource("Title")</title>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-extension.css" rel="stylesheet" />
    <script src="~/Scripts/Plugins/autocomplete.js"></script>
    <script src="~/Scripts/Plugins/globalParams.js"></script>
    <link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />
    <link href="~/Content/themes/base/jquery-ui-extension.css" rel="stylesheet" />
    <meta charset=utf-8 />
    
    <script>
        $(document).ready(function () {
            $("#tableRefresh").click(function (e) {
                window["@Model.tableRefresh"]();
            });
        });
    </script>
    <script type="text/javascript" title="Initialize">
        var globalParams = new ParametrosGlobales;
        $(document).ready(function(){
            var iniVal = @Html.Raw(Json.Encode(Model.SelectedValue));
            if(iniVal == null || iniVal == 0){
                var aux = sessionStorage.getItem("FilterID");
                if(aux == null || aux == ""){
                    $("#SelectedValue").val("");
                    $("#temporaryDepositsTable").hide();
                }else{
                    $("#SelectedValue").val(aux);
                    globalParams.addParam("DistributionCenterID", aux);
                    $("#temporaryDepositsTable").show();
                }
            }else{
                globalParams.addParam("DistributionCenterID", iniVal);
                $("#temporaryDepositsTable").show();
            }
        });
    </script>

    <script type="text/javascript" title="Clear Form Data">
        $(document).ready(function () {
            var aux = sessionStorage.getItem("FilterID");
            sessionStorage.clear();
            if(aux != null && aux != ""){
                sessionStorage.setItem("FilterID", aux);
            }
        });
    </script>

    <script type="text/javascript" title="Autocomplete">
    $(document).ready(function () {
        $("#SelectedValue").autocompletar({
            url: '@Url.Action("DistributionCenterAutocomplete", "DepositsABM")',
            seleccion: function (event, ui) {
                $('#SelectedValue').val(ui.item.id);
                globalParams.addParam("DistributionCenterID", ui.item.id);
                $("#temporaryDepositsTable").show();
                window["@Model.tableRefresh"]();
                var link = "<a id=\"addTemporalDeposit\" class=\"btn btn-success btn-lg btn-xs\" href = \"@Url.Action("Index", "TemporaryDepositsForms", new { DistributionCenterID = -1 })\"><span class=\"glyphicon glyphicon-plus\"></span</a>";
                link = link.replace("-1", ui.item.id);
                $("#addTemporalDeposit").replaceWith(link);
                sessionStorage.setItem("FilterID",ui.item.id);
                return false;
            },
            keyup: function (event, ui) {
                var valor = $("#SelectedValue").val();
                if (valor == null || valor == "") {
                    sessionStorage.setItem("FilterID","");
                    $("#temporaryDepositsTable").hide();
                }
            }
        });
    });
    </script>

</head>
<body>
    <div class="container">
        <div class="row">
            <h3>@Html.Resource("Title")</h3>
            @if (@Model.Message != null && @Model.Error != null && @Model.Message != "") {
                if (@Model.Error == true) {
                    <div class="alert alert-dismissable alert-danger">
                        <button type="button" class="close" data-dismiss="alert">×</button>
                        @Model.Message
                    </div>
                } else {
                    <div class="alert alert-dismissable alert-success">
                        <button type="button" class="close" data-dismiss="alert">×</button>
                        @Model.Message
                    </div>
                }
            }
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="row">
                        <div class="col-sm-1">
                            @if (Model.SelectedValue == null || Model.SelectedValue == 0) {
                                <a class="btn btn-success btn-xs" id="addTemporalDeposit" href="@Url.Action("Index","TemporaryDepositsForms")">
                                    <span class="glyphicon glyphicon-plus"></span>
                                </a>
                            } else {
                                <a class="btn btn-success btn-xs" id="addTemporalDeposit" href="@Url.Action("Index", "TemporaryDepositsForms", new { DistributionCenterID = Model.SelectedValue })">
                                    <span class="glyphicon glyphicon-plus"></span>
                                </a>
                            }
                            <a id="tableRefresh" class="btn btn-default btn-xs">
                                <span class="glyphicon glyphicon-refresh"></span>
                            </a>
                        </div>
                        <label class="col-sm-2 control-label">@Html.Resource("SelectDC"):</label>
                        <div class="col-sm-3">
                            @Html.TextBoxFor(model => model.SelectedValue, new { @class = "form-control input-sm" })
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div id="temporaryDepositsTable" hidden="hidden">
            @{Html.RenderPartial("~/Views/DistributionCenter/Tables/_TemporaryDepositsTable.cshtml", new TableAjaxViewModel(@Model.tableID) {
                AjaxRequest = @Url.Action("GetTable","TemporaryDepositsABM"),
                DeleteAction = "Delete",
                DeleteController = "TemporaryDepositsABM",
                DeleteText = Resources.FormsResources.Delete,
                DeleteConfirmMessage = String.Format(Resources.Messages.SureToDelete, Resources.Resources.TemporaryDepositWArt),
                RefreshFunction = @Model.tableRefresh,
                ServerProcessing = false
            });}
        </div>
    </div>
</body>
</html>