trunk/Penates/Penates/Models/ViewModels/Transactions/ProductsReceptions/ContainersAndLocationAssignationModel.cs
using Penates.Utils.Objects;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Penates.Models.ViewModels.Transactions.ProductsReceptions
{
    public class ContainersAndLocationAssignationModel
    {
        public ContainersAndLocationAssignationModel()
        {
            this.Error = false;
            this.Message = "";
            this.productsAssignations = new List<ProductAssignation>();
        }

        public bool? Error { get; set; }

        public string Message { get; set; }

        public List<ProductAssignation> productsAssignations { get; set; }

        
    }
}

trunk/Penates/Penates/Models/ViewModels/Transactions/ProductsReceptions/ExternalLocationAssignationModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Penates.Models.ViewModels.Transactions.ProductsReceptions
{
    public class ExternalLocationAssignationModel
    {
        public ExternalLocationAssignationModel()
        {
            this.Error = false;
            this.Message = ""; 
        }

        public bool Error { set; get; }

        public string Message { set; get; }                       

        public string DistributionCenterDestiny { get; set; }

        public SortedDictionary<string, List<long>> boxesIdsPerProductName { get; set; }


    }
}

trunk/Penates/Penates/Controllers/Transactions/OrderFormController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Penates.Models.ViewModels.Forms;
using Penates.Database;
using System.Drawing;
using Penates.Utils;
using Penates.Utils.Keepers;
using Penates.Services.ABMs;
using System.Data.Entity.Core;
using Penates.Exceptions.Database;
using Penates.Models;
using Penates.Models.ViewModels.ABMs;
using Penates.Controllers.ABMs;
using Penates.Interfaces.Services;
using Penates.Models.ViewModels.Transactions;
using Penates.Services.Transactions;
using Penates.Utils.JSON.TableObjects;
using Penates.Services;
using Penates.Utils.Enums;
using Penates.Exceptions;


namespace Penates.Controllers
{
    [RoleValidation(RoleType.SU, RoleType.InventoryChief, RoleType.Common)]
    public class OrderFormController : Controller
    {
        public ActionResult Index(OrderViewModel model){
            return this.OrderForm(model);
        }

        public ActionResult OrderForm(OrderViewModel model) {
            try {
                model.OldOrderID = model.OrderID;
                model.OldSupplierID = model.SupplierID;
                return View("~/Views/Transactions/Orders/OrderForm.cshtml", model);
            } catch (DatabaseException ex) {
                ErrorModel error = new ErrorModel(Resources.Errors.DatabaseError, ex.Message, "SupplierFormsController", "SupplierForm");
                return View("~/Views/Error/ErrorDisplay.cshtml", error);
            } catch (Exception e) {
                ErrorModel error = new ErrorModel(Resources.Errors.DatabaseError, e, "SupplierFormsController", "SupplierForm");
                return View("~/Views/Error/ErrorDisplay.cshtml", error);
            }
        }

        public JsonResult ProductAutocomplete(string term, string OrderID, long? SupplierID) {
            try {
                IOrderService service = new OrderService();
                IProductService productService = new ProductService();
                IQueryable<Product> items = service.getAutocompleteItems(term, OrderID, SupplierID);
                var json = productService.toJsonAutocomplete(items);
                return Json(json, JsonRequestBehavior.AllowGet);
            } catch (DatabaseException ex) {
                Response.StatusCode = 504;
                Response.StatusDescription = ex.title;
                Response.Write(ex.Message);
                return null;
            } catch (Exception e) {
                Response.StatusCode = 504;
                Response.StatusDescription = Resources.Errors.DatabaseError;
                Response.Write(e.Message);
                return null;
            }
        }

        public ActionResult FormEdit(string orderID, long supplierID) {
            IOrderService service = new OrderService();
            try {
                OrderViewModel model = service.getData(orderID, supplierID);
                if (model == null) {//Si no encontre el producto agrego el error para que lo muestre
                    model = new OrderViewModel();
                    model.Error = String.Format(Resources.Messages.ItemNotFound, Resources.Resources.OrderWArt, orderID);
                }
                return this.OrderForm(model);
            } catch (DatabaseException ex) {
                ErrorModel error = new ErrorModel(Resources.Errors.DatabaseError, ex.Message, "SupplierFormsController", "FormEdit");
                return View("~/Views/Error/ErrorDisplay.cshtml", error);
            } catch (Exception e) {
                ErrorModel error = new ErrorModel(Resources.Errors.DatabaseError, e, "SupplierFormsController", "FormEdit");
                return View("~/Views/Error/ErrorDisplay.cshtml", error);
            }
        }

        public ActionResult ProductLoad(jQueryDataTableParamModel param, string OrderID, long? SupplierID) {
            try {
                IOrderService os = new OrderService();
                ICollection<SupplierOrderItem> query = os.getItems(OrderID, SupplierID);
                IOrderItemsService ois = new OrderItemsService();
                List<OrderItemsTableJson> table = ois.toJsonArray(query);
                return Json(new {
                    sEcho = param.sEcho,
                    aaData = table
                },
                            JsonRequestBehavior.AllowGet);
            } catch (DatabaseException ex) {
                ErrorModel errorModel = new ErrorModel(ex.title, ex.Message, ex, "OrderFormsController", "ProductLoad");
                return View("~/Views/Error/ErrorDisplay.cshtml", errorModel);
            } catch (Exception e) {
                ErrorModel errorModel = new ErrorModel(Resources.Errors.DatabaseError, e, "OrderFormsController", "ProductLoad");
                return View("~/Views/Error/ErrorDisplay.cshtml", errorModel);
            }
        }

        /// <summary> Trato el POST del formulario de Producto </summary>
        /// <param name="prod">El modelo con los datos del producto</param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Save(OrderViewModel model) {
            if (ModelState.IsValid) {
                IOrderService orderService = new OrderService();
                try {
                    if (orderService.Save(model)) {
                        ABMViewModel abm = new ABMViewModel();
                        abm.Message = String.Format(Resources.Messages.OperationSuccessfull, Resources.Resources.OrderWArt);
                        abm.Error = false;
                        return RedirectToAction("Index", "OrdersABM", new { Message = abm.Message, Error = abm.Error });
                    } else {
                        ModelState.AddModelError("Error", Resources.Errors.SPError);
                    }
                } catch (ForeignKeyConstraintException infe) {
                    ModelState.AddModelError("SupplierID", infe.Message);
                } catch (DuplicatedKeyException) {
                    ModelState.AddModelError("OrderID", String.Format(Resources.ExceptionMessages.ItemAlreadyExist,
                        Resources.Resources.Order));
                    ModelState.AddModelError("SupplierID", String.Format(Resources.ExceptionMessages.ItemAlreadyExist,
                        Resources.Resources.Order));
                } catch (IDNotFoundException infe) {
                    ErrorModel error = new ErrorModel(infe.title, infe.Message, infe, "SupplierFormsController", "DeleteProduct");
                    return View("~/Views/Error/ErrorDisplay.cshtml", error);
                } catch (DatabaseException ex) {
                    ErrorModel error = new ErrorModel(ex.title, ex.Message, ex, "SupplierFormsController", "DeleteProduct");
                    return View("~/Views/Error/ErrorDisplay.cshtml", error);
                } catch (Exception e) {
                    ErrorModel error = new ErrorModel(e.Message, e, "SupplierFormsController", "DeleteProduct");
                    return View("~/Views/Error/ErrorDisplay.cshtml", error);
                }
            }
            return View("~/Views/Transactions/Orders/OrderForm.cshtml", model);
        }

        /// <summary>Elimina el proveedor con determinado id del sistema /// </summary>
        /// <param name="id">Id del producto a eliminar</param>
        /// <returns>El menu de ABM o en caso de tener una constrain la lista de constrains</returns>
        public ActionResult Delete(string orderID, long supplierID) {
            IOrderService service = new OrderService();
            try {
                ABMViewModel model = new ABMViewModel();
                if (service.isCanceled(orderID, supplierID)) {
                    bool result = service.Restore(orderID, supplierID);
                    if (result) {
                        model.Message = String.Format(Resources.Messages.RestoredItem, Resources.Resources.OrderWArt);
                        model.Error = false;
                    } else {
                        model.Message = String.Format(Resources.Errors.OperationUnsaccessfull);
                        model.Error = true;
                    }
                    return RedirectToAction("Index", "OrdersABM", new { Message = model.Message, Error = model.Error });
                } else {
                    try {
                        bool result = service.Cancel(orderID, supplierID);
                        if (result) {
                            model.Message = String.Format(Resources.Messages.CancelledItem, Resources.Resources.OrderWArt);
                            model.Error = false;
                        } else {
                            model.Message = String.Format(Resources.Errors.OperationUnsaccessfull);
                            model.Error = true;
                        }
                        return RedirectToAction("Index", "OrdersABM", new { Message = model.Message, Error = model.Error });

                    } catch (DeleteConstrainException) {
                        ConstraintViewModel models = service.getConstrains();
                        OrderViewModel mod = service.getData(orderID, supplierID);
                        ModelState.AddModelError("Error", models.Title + ": " + models.Message);
                        return View("~/Views/Transactions/Orders/OrderForm.cshtml", mod);
                    }
                }
            } catch (DatabaseException ex) {
                ErrorModel error = new ErrorModel(ex.title, ex.Message, ex, "SupplierFormsController", "DeleteProduct");
                return View("~/Views/Error/ErrorDisplay.cshtml", error);
            } catch (MyException ex) {
                ErrorModel error = new ErrorModel(ex.title, ex.Message, ex, "SupplierFormsController", "DeleteProduct");
                return View("~/Views/Error/ErrorDisplay.cshtml", error);
            } catch (Exception e) {

trunk/Penates/Penates/Controllers/Transactions/Sales/SalesABMController.cs
using Penates.Database;
using Penates.Exceptions.Database;
using Penates.Interfaces.Services;
using Penates.Models;
using Penates.Models.ViewModels.ABMs;
using Penates.Services;
using Penates.Services.Transactions;
using Penates.Utils;
using Penates.Utils.Enums;
using Penates.Utils.JSON.TableObjects;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Penates.Controllers.Transactions.Sales
{
    public class SalesABMController : Controller
    {
        [RoleValidation(RoleType.SU, RoleType.InventoryChief, RoleType.Common)]
        public ActionResult Index(ABMViewModel model, long? DistributionCenterID) {
            if (model == null) {
                model = new ABMViewModel();
            }
            if (DistributionCenterID.HasValue) {
                model.SelectedValue = DistributionCenterID.Value;
            }
            List<SelectListItem> anulatedList = new List<SelectListItem>();
            SelectListItem i = new SelectListItem();
            i.Text = Resources.Resources.All;
            i.Value = AnulatedTypes.ALL.getTypeNumber().ToString();
            anulatedList.Add(i);
            i = new SelectListItem();
            i.Text = Penates.App_GlobalResources.Forms.ModelFormsResources.Internal;
            i.Value = AnulatedTypes.VALID.getTypeNumber().ToString(); ;
            anulatedList.Add(i);
            i = new SelectListItem();
            i.Text = Penates.App_GlobalResources.Forms.ModelFormsResources.External;
            i.Value = AnulatedTypes.ANULATED.getTypeNumber().ToString(); ;
            anulatedList.Add(i);
            ViewBag.AnulatedList = anulatedList;
            return View("~/Views/Transactions/Sales/SalesABM.cshtml", model);
        }

        [RoleValidation(RoleType.SU, RoleType.InventoryChief, RoleType.Common)]
        public ActionResult GetTable(jQueryDataTableParamModel param, long? DistributionCenterID, long? ClientID, int? anulated) {
            try {
                ISaleService service = new SaleService();
                int sortColumnIndex = Convert.ToInt32(Request["iSortCol_0"]);
                string sortDirection = Request["sSortDir_0"];
                IQueryable<Sale> query = service.getData();
                query = service.filterByDistributionCenter(query, DistributionCenterID);
                query = service.filterByClient(query, ClientID);
                query = service.filterByAnulated(query, anulated);
                query = service.sort(query, sortColumnIndex, sortDirection);
                long total = query.Count(); //El total sin paginacion
                Paginator<Sale> pag = new Paginator<Sale>(query);
                query = pag.page(param.iDisplayStart, param.iDisplayLength);
                List<SaleTableJson> result = service.toJsonArray(query);
                long count = result.Count();
                return Json(new {
                    sEcho = param.sEcho,
                    iTotalRecords = count,
                    iTotalDisplayRecords = total,
                    aaData = result
                },
                            JsonRequestBehavior.AllowGet);
            } catch (DatabaseException ex) {
                ErrorModel errorModel = new ErrorModel(ex.title, ex.Message, ex, this.ControllerContext.RouteData.Values["controller"].ToString(), this.ControllerContext.RouteData.Values["action"].ToString());
                return View("~/Views/Error/ErrorDisplay.cshtml", errorModel);
            } catch (Exception e) {
                ErrorModel errorModel = new ErrorModel(Resources.Errors.DatabaseError, e, this.ControllerContext.RouteData.Values["controller"].ToString(), this.ControllerContext.RouteData.Values["action"].ToString());
                return View("~/Views/Error/ErrorDisplay.cshtml", errorModel);
            }
        }

        /// <summary>Elimina el centro de distribucion con determinado id del sistema /// </summary>
        /// <param name="id">Id del producto a eliminar</param>
        /// <returns>El menu de ABM o en caso de tener una constrain la lista de constrains</returns>
        [RoleValidation(RoleType.SU, RoleType.InventoryChief, RoleType.Common)]
        public ActionResult Anulate(long SaleID) {
            ISaleService service = new SaleService();
            try {
                Status result = service.Anulate(SaleID);
                if (result.Success) {
                    return Json(new {
                        title = Resources.Messages.OperationSuccessfull,
                        message = result.Message
                    }, JsonRequestBehavior.AllowGet);
                } else {
                    Response.StatusCode = 511;
                    Response.StatusDescription = Resources.Errors.OperationUnsaccessfull;
                    Response.Write(result.Message);
                    return null;
                }
            } catch (DatabaseException ex) {
                Response.StatusCode = 511;
                Response.StatusDescription = ex.title;
                if (String.IsNullOrEmpty(ex.Message)) {
                    Response.Write("Error");
                } else {
                    Response.Write(ex.Message);
                }
                return null;
            } catch (Exception e) {
                Response.StatusCode = 511;
                Response.StatusDescription = Resources.Errors.OperationUnsaccessfull;
                Response.Write(e.Message);
                return null;
            }
        }

        [RoleValidation(RoleType.All)]
        public JsonResult Autocomplete(string term, long? DistributionCenterID, long? ClientID, bool? annulated) {
            try {
                ISaleService service = new SaleService();
                var items = service.getAutocomplete(term, DistributionCenterID, ClientID, annulated);
                var json = service.toJsonAutocomplete(items);
                return Json(json, JsonRequestBehavior.AllowGet);
            } catch (DatabaseException ex) {
                Response.StatusCode = 504;
                Response.StatusDescription = ex.title;
                Response.Write(ex.Message);
                return null;
            } catch (Exception e) {
                Response.StatusCode = 504;
                Response.StatusDescription = Resources.Errors.DatabaseError;
                Response.Write(e.Message);
                return null;
            }
        }
    }
}

trunk/Penates/Penates/Views/Transactions/Orders/OrderForm.cshtml
@model Penates.Models.ViewModels.Transactions.OrderViewModel
@using Penates.Helpers
@using Penates.Models.ViewModels

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!doctype html>
<html>
<head>
    <title>@Html.Resource("Title")</title>
    <meta charset="utf-8">
    <link href="~/Content/forms/images-sizes.css" rel="stylesheet" /> <!--Para hacer resize de las Imagenes-->
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-background.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-extension.css" rel="stylesheet" />
    <link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />
    <link href="~/Content/themes/base/jquery-ui-extension.css" rel="stylesheet" />
    <script type="text/javascript">
        $(document).ready(function () {
            $('#Delete').click(function () {
                if (confirm('@String.Format(Resources.Messages.SureToDelete, Resources.Resources.OrderWArt, Model.OrderID)')) {
                    window.location.href = $(this).data('url');
                }
            });
        });
    </script>
    <script type="text/javascript" title="Datepicker">
        $(document).ready(function () {
            $("#OrderDate").val('@Model.OrderDate.ToLongDateString()');
        $("#OrderDate").datepicker({
            changeMonth: true,
            changeYear: true,
            dateFormat: "DD, MM d, yy",
            setDate: '@Model.OrderDate'
        });
        $("#OrderDate").datepicker("option", "showAnim", "fold");
    });
    </script>
</head>

<body>
    <div class="container">
            <h2>@Html.Resource("Title")</h2>
        @using(Html.BeginForm("Save", "OrderForm", FormMethod.Post, new { @class="form-horizontal", @id="supplier-form", autocomplete="on", @enctype="multipart/form-data" })){
            @Html.ValidationMessageFor(m => m.Error)
                <fieldset>
                    <legend></legend>
                    <div class="form-group">
                        <label class="col-lg-2 control-label">* @Html.DisplayNameFor(m => m.OrderID):</label>
                        <div class="col-lg-4">
                            @Html.TextBoxFor(m => m.OrderID, new { required = "required", @class = "form-control" })
                            <div class="form-group" hidden>
                                @Html.TextBoxFor(m => m.OldOrderID, new {@class = "form-control" })
                            </div>
                                @Html.ValidationMessageFor(m => m.OrderID)
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-lg-2 control-label">* @Html.DisplayNameFor(m => m.SupplierName):</label>
                        <div class="col-lg-4">
                            @Html.TextBoxFor(m => m.SupplierName, new { required = "required", @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.SupplierName)
                        </div>
                        <label class="col-lg-2 control-label">* @Html.DisplayNameFor(m => m.SupplierID):</label>
                        <div class="col-lg-4">
                            @Html.TextBoxFor(m => m.SupplierID, new { required = "required", disabled = "disabled", @class = "form-control" })
                            <div class="form-group" hidden>
                                @Html.TextBoxFor(m => m.SupplierID, new { @class = "form-control" })
                                @Html.TextBoxFor(m => m.OldSupplierID, new { @class = "form-control" })
                            </div>
                            @Html.ValidationMessageFor(m => m.SupplierID)
                        </div>
                    </div>
                    @if (!String.IsNullOrEmpty(Model.OrderID)) {
                        if (Model.Received) {
                            <div class="form-group">
                                <label class="col-lg-2 control-label">* @Html.DisplayNameFor(m => m.OrderDate):</label>
                                <div class="col-lg-4">
                                    @Html.TextBoxFor(m => m.OrderDate, new { required = "required", @class = "form-control" })
                                </div>
                                @Html.ValidationMessageFor(m => m.OrderDate)
                                <label class="col-lg-2 control-label">* @Html.DisplayNameFor(m => m.Received):</label>
                                <div class="col-lg-4">
                                    <h4 class="text-success text-center"><b>@Html.Resource("Received")</b></h4>
                                </div>
                            </div>
                        } else {
                            <div class="form-group">
                                <label class="col-lg-2 control-label">* @Html.DisplayNameFor(m => m.OrderDate):</label>
                                <div class="col-lg-4">
                                    @Html.TextBoxFor(m => m.OrderDate, new { required = "required", @class = "form-control" })
                                </div>
                                @Html.ValidationMessageFor(m => m.OrderDate)
                                <label class="col-lg-2 control-label">* @Html.DisplayNameFor(m => m.Received):</label>
                                <div class="col-lg-4">
                                    <h4 class="text-danger text-center"><b>@Html.Resource("NotReceived")</b></h4>
                                </div>
                            </div>
                        }
                    }
                    <div class="form-group">
                        <label class="col-lg-2 control-label">* @Html.DisplayNameFor(m => m.Total):</label>
                        <div class="col-lg-4">
                            <div class="input-group">
                                <span class="input-group-addon">$</span>
                                @Html.TextBoxFor(m => m.Total, new { required = "required", disabled = "disabled", @class = "form-control form-number-input" })
                            </div>
                        </div>
                    </div>
                    <br />
                    <fieldset>
                        <legend>@Html.Resource("SearchAndAddProducts")</legend>
                        @{Html.RenderPartial("~/Views/ABMs/_SearchAndAddModal.cshtml", new SearchAndAddViewModelWithModal() {
                            TablePartialView = "~/Views/Transactions/Tables/_OrderItemsTable.cshtml",
                            TableAjaxRequest = Url.Action("ProductLoad", "OrderForm"),
                            AjaxRequest = @Url.Action("ProductAutocomplete", "OrderForm"),
                            Params = new {OrderID = Model.OldOrderID, SupplierID = Model.OldSupplierID},
                            SubmitAction = "AddProduct",
                            SubmitController = "OrderItemsForm",
                            ConfirmMessage = @String.Format(Resources.Messages.SureToAdd, Resources.Resources.Product),
                            TableDeleteAction = "UnassignProduct",
                            TableDeleteController = "OrderItemsForm",
                            TableDeleteText = @Resources.FormsResources.Unassign,
                            TableDeleteConfirmMessage = String.Format(Resources.Messages.SureToUnassign, Resources.Resources.ProductWArt, Resources.Resources.OrderWArt),
                            TableServerProcessing = false,
                            ModalURL = Url.Action("ItemsFormModal", "OrderItemsForm"),
                            ModalEditURL = Url.Action("FormEdit", "OrderItemsForm")
                        });}
                    </fieldset>
                    
                    <div class="btn-toolbar">
                        <button type="submit" class="btn btn-success" id="Save" value="Save">@Resources.FormsResources.Save</button>
                        @Html.ActionLink(@Resources.FormsResources.Cancel, "Index", "OrdersABM", null, new { @class = "btn btn-default" })
                        <button type="button" class="btn btn-danger" id="Delete" data-url="@Url.Action("Delete", "SupplierForms", new { id = Model.SupplierID })">@Resources.FormsResources.Delete</button>
                        @Html.ActionLink(@Html.Resource("ViewSupplier"), "FormEdit", "SupplierForms", new { id = Model.SupplierID }, new { @class = "btn btn-default" })
                    </div>
                </fieldset>
            }
        </div>
    <script src="~/Scripts/ABMs/Forms/imageLoad.js"></script>
</body>
</html>

trunk/Penates/Penates/Views/Transactions/Orders/OrdersABM.cshtml
@model Penates.Models.ViewModels.ABMs.ABMViewModel
@using Penates.Models
@using Penates.Models.ViewModels.Transactions

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!doctype html>
<html>
<head>
    <title>@Html.Resource("Title")</title>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-extension.css" rel="stylesheet" />
    <script src="~/Scripts/Plugins/globalParams.js"></script>
    <meta charset=utf-8 />
    
    <style>
        .ui-autocomplete {
            max-height: 300px;
            overflow-y: auto;
            /* prevent horizontal scrollbar */
            overflow-x: hidden;
        }
        /* IE 6 doesn't support max-height
            * we use height instead, but this forces the menu to always be this tall
            */
        * html .ui-autocomplete {
            height: 300px;
        }
    </style>

    <script>
        $(document).ready(function () {
            $("#tableRefresh").click(function (e) {
                window["@Model.tableRefresh"]();
            });

            $("#SelectedValue").change(function (e) {
                window["@Model.tableRefresh"]();
            });
        });
    </script>

    <script type="text/javascript" title="Supplier Filter">
        var globalParams = new ParametrosGlobales();
        $(document).ready(function () {
        $("#supplierFilter").autocompletar({
            url: '@Url.Action("SupplierAutocomplete", "OrdersABM")',
            seleccion: function (event, ui) {
                globalParams.addParam("FilterID", ui.item.id.SupplierID);
                window["@Model.tableRefresh"]();
                    return false;
                },
                keyup: function (event) {
                    var value = $("#supplierFilter").val();
                    if (value == null || value == "") {
                        globalParams.deleteParam("FilterID");
                        window["@Model.tableRefresh"]();
                    }
                }
            });
        });
    </script>
</head>
<body>
    <div id="modalDiv">
        <!-- Modal -->
        <div class="modal fade" id="OrderFormModal" tabindex="-1" role="dialog" aria-labelledby="OrderFormModal" aria-hidden="true">
            @{Html.RenderPartial("~/Views/Transactions/Orders/_OrderFormModal.cshtml", new OrderViewModel());}
        </div>
    </div>

    <div class="container">
        <div class="row">
            <h3>@Html.Resource("Title")</h3>
            @if (@Model.Message != null && @Model.Error != null && @Model.Message != "") {
                if (@Model.Error == true) {
                    <div class="alert alert-dismissable alert-danger">
                        <button type="button" class="close" data-dismiss="alert">×</button>
                        @Model.Message
                    </div>
                } else {
                    <div class="alert alert-dismissable alert-success">
                        <button type="button" class="close" data-dismiss="alert">×</button>
                        @Model.Message
                    </div>
                }
            }
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="row">
                        <div class="col-sm-2">
                            <a class="btn btn-success btn-lg btn-xs" data-toggle="modal" data-target="#OrderFormModal">
                                <span class="glyphicon glyphicon-plus"></span>
                            </a>
                            <a id="tableRefresh" class="btn btn-default btn-lg btn-xs">
                                <span class="glyphicon glyphicon-refresh"></span>
                            </a>
                        </div>
                        <div class="col-sm-4">
                            @String.Format(Resources.FormsResources.FilterBy, Resources.Resources.Supplier):
                        </div>
                        <div class="col-sm-6">
                            <input type="text" id="supplierFilter" name="objectSearch" />
                        </div>
                    </div>
                </div>
            </div>
            @{Html.RenderPartial("~/Views/Transactions/Tables/_OrderTable.cshtml", new TableAjaxViewModel("Order") {
                  AjaxRequest = Url.Action("ABMAjax", "OrdersABM"),
                  DeleteAction = "Delete",
                  DeleteController = "OrdersABM",
                  DeleteText = Resources.FormsResources.Cancel,
                  DeleteConfirmMessage = String.Format(Resources.Messages.SureToCancel, Resources.Resources.OrderWArt),
                  ToggleDeleteMessage = true,
                  DeleteText2 = Resources.FormsResources.Restore,
                  DeleteConfirmMessage2 = String.Format(Resources.Messages.SureToRestore, Resources.Resources.OrderWArt),
                  RefreshFunction = @Model.tableRefresh
              });}
        </div>
    </div>
</body>
</html>